name: Run Tests

on:
    push:
        paths:
            - '**.js'
            - 'package.json'

jobs:
    build:
        runs-on: 'ubuntu-18.04'

        steps:
            -   uses: actions/checkout@v2

            -   name: Use Node.js
                uses: actions/setup-node@v1
                with:
                    node-version: 'latest'

            -   name: Install npm dependencies
                run: npm install

            -   run: yarn test
